services:
- type: web
  name: app
  buildCommand : yarn build
  startCommand: yarn next start
  envVars:
  - key: LOST_PIXEL_DISABLE_TELEMETRY
    value: '1'
  disk:
    name: app
    mountPath: /app
    sizeGB: 10
